car_showroom/cars/urls.py
from django.urls import path, include

from car_showroom.cars.views import car_details, car_edit, car_delete, car_add

urlpatterns = (
    path('add/', car_add, name='car add'),
    path('<slug:slug>/<int:user_id>/', include([
        path('', car_details, name='car details'),
        path('edit/', car_edit, name='car edit'),
        path('delete/', car_delete, name='car delete'),
    ])),
)

car_showroom/urls.py
from django.contrib import admin
from django.urls import path, include

# from car_showroom.core.exeption_handler import page_not_found_handler

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('car_showroom.common.urls')),
    path('accounts/', include('car_showroom.accounts.urls')),
    path('cars/', include('car_showroom.cars.urls')),
]


# handler_404 = page_not_found_handler
# handler500 = handler500

car_showroom/cars/models.py
from django.contrib.auth import get_user_model
from django.core.validators import MinValueValidator, MinLengthValidator
from django.db import models
from django.db.models import Q
from django.utils.text import slugify

UserModel = get_user_model()


class Car(models.Model):
    TYPE_CHOICES = (
        ('Sports Car', 'Sports Car'),
        ('Pickup', 'Pickup'),
        ('Crossover', 'Crossover'),
        ('Other', 'Other'),
    )
    TYPE_MAX_LEN = 20

    MODEL_MAX_LEN = 20
    MODEL_MIN_LEN = 2

    YEAR_OF_PRODUCTION_VERBOSE_NAME = 'Year of production'
    YEAR_MIN_VALUE = 1980
    YEAR_VALIDATION_ERROR_MESSAGE = 'This car is too old!'

    IMAGE_URL_VERBOSE_NAME = 'Image URL'

    PRICE_MIN_VALUE = 30000
    PRICE_VALIDATION_ERROR_MESSAGE = 'This car is too cheap to stay in the showroom!'

    HORSE_POWER_VERBOSE_NAME = 'Horse Power'
    HORSE_POWER_MIN_VALUE = 100
    HORSE_POWER_VALIDATION_ERROR_MESSAGE = 'This car is too weak to stay in the showroom!'

    type = models.CharField(
        max_length=TYPE_MAX_LEN,
        choices=TYPE_CHOICES,
        null=False,
        blank=False,
    )

    model = models.CharField(
        max_length=MODEL_MAX_LEN,
        validators=(
            MinLengthValidator(MODEL_MIN_LEN),
        ),
        null=False,
        blank=False,
    )

    year_of_production = models.PositiveIntegerField(
        verbose_name=YEAR_OF_PRODUCTION_VERBOSE_NAME,
        validators=(
            MinValueValidator(YEAR_MIN_VALUE, message=YEAR_VALIDATION_ERROR_MESSAGE),
        ),
        null=False,
        blank=False,
    )

    image_url = models.URLField(
        verbose_name=IMAGE_URL_VERBOSE_NAME,
        null=False,
        blank=False,
    )

    price = models.FloatField(
        validators=(
            MinValueValidator(PRICE_MIN_VALUE, message=PRICE_VALIDATION_ERROR_MESSAGE),
        ),
        null=False,
        blank=False,
    )

    horse_power = models.PositiveIntegerField(
        verbose_name=HORSE_POWER_VERBOSE_NAME,
        validators=(
            MinValueValidator(HORSE_POWER_MIN_VALUE, message=HORSE_POWER_VALIDATION_ERROR_MESSAGE),
        )
    )

    description = models.TextField(
        null=True,
        blank=True
    )

    user = models.ForeignKey(
        UserModel,
        on_delete=models.CASCADE,
        null=True
    )

    slug = models.SlugField(
        unique=True,
        null=False,
        blank=True,
    )

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        if not self.slug:
            self.slug = slugify(f'{self.id}-{self.model}')

        return super().save(*args, **kwargs)

    def __str__(self):
        return self.model

car_showroom/common/models.py
import datetime

from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError
from django.db import models

from car_showroom.cars.models import Car

UserModel = get_user_model()


class CarLike(models.Model):
    car = models.ForeignKey(
        Car,
        on_delete=models.CASCADE,
        null=False,
        blank=True
    )

    user = models.ForeignKey(
        UserModel,
        on_delete=models.CASCADE,
    )


class CarComment(models.Model):
    CAR_COMMENT_VERBOSE_NAME = ''
    MAX_TEXT_LENGTH = 100
    text = models.CharField(
        verbose_name=CAR_COMMENT_VERBOSE_NAME,
        max_length=MAX_TEXT_LENGTH,
        null=False,
        blank=False,
    )

    publication_date_and_time = models.DateTimeField(
        auto_now_add=True,
        blank=True,
        null=False,
    )

    car = models.ForeignKey(
        Car,
        on_delete=models.CASCADE,
        null=False,
        blank=True,
    )

    user = models.ForeignKey(
        UserModel,
        on_delete=models.CASCADE,
    )

    class Meta:
        ordering = ['publication_date_and_time']


class CarTestDrive(models.Model):
    user = models.ForeignKey(
        UserModel,
        on_delete=models.CASCADE,
    )

    car = models.ForeignKey(
        Car,
        on_delete=models.CASCADE,
        null=False,
        blank=True,
    )

    test_drive_date = models.DateField(
        verbose_name='Test drive date',
        default=datetime.datetime.now(),
        null=False,
        blank=False
    )

    def save(self, *args, **kwargs):
        if self.test_drive_date < datetime.date.today():
            raise ValidationError("The date cannot be in the past!")
        super(CarTestDrive, self).save(*args, **kwargs)

    def __str__(self):
        return f'{self.user} want to test {self.car.model}'

    class Meta:
        ordering = ['test_drive_date']

car_showroom/cars/forms.py
from django import forms

from car_showroom.cars.models import Car


class CarBaseForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(CarBaseForm, self).__init__(*args, **kwargs)
        self.fields['description'].widget.attrs['size'] = 30

    class Meta:
        model = Car
        fields = ('type', 'model', 'year_of_production', 'price', 'horse_power', 'image_url', 'description')

    widgets = {
        'description': forms.TextInput(attrs={'rows': 5, 'cols': 15}),
    }


class CarDetailsForm(CarBaseForm):
    pass


class CarCreateForm(CarBaseForm):
    pass


class CarEditForm(CarBaseForm):
    pass


class CarDeleteForm(CarBaseForm):
    disabled_fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for _, field in self.fields.items():
            field.widget.attrs['disabled'] = 'disabled'
            field.required = False

    def save(self, commit=True):
        self.instance.delete()
        return self.instance

car_showroom/cars/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required, user_passes_test
from django.core.exceptions import ObjectDoesNotExist
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404

from car_showroom.cars.forms import CarDetailsForm, CarEditForm, CarCreateForm, CarDeleteForm
from car_showroom.cars.models import Car
from car_showroom.cars.utils import get_car_by_model_and_user_id
from car_showroom.common.forms import CommentCarForm
from car_showroom.common.models import CarLike, CarTestDrive
from car_showroom.common.utils import user_has_test_drive_with_current_car

UserModel = get_user_model()


def car_details(request, slug, user_id):
    try:
        car = get_car_by_model_and_user_id(slug, user_id)
        user_has_test_drive = user_has_test_drive_with_current_car(user_id=request.user.pk, car_id=car.pk)
        user_like_cars = CarLike.objects.filter(car_id=car.pk, user_id=request.user.pk)

        context = {
            'car': car,
            'has_user_liked_car': user_like_cars,
            'is_owner': car.user == request.user,
            'likes_count': car.carlike_set.count(),
            'comment_form': CommentCarForm(),
            'user_has_test_drive': user_has_test_drive
        }

    except ObjectDoesNotExist as ex:
        return render(request, 'exception-handling/car-details-error-page.html')
    return render(request, 'cars/car-details-page.html', context)


def car_edit(request, slug, user_id):
    try:
        car = get_car_by_model_and_user_id(slug, user_id)

        if not car.user == request.user:
            return redirect('home page', user_id=user_id, slug=slug)

        if request.method == 'GET':
            form = CarEditForm(instance=car)
        else:
            form = CarEditForm(request.POST, instance=car)
            if form.is_valid():
                form.save()
                return redirect('car details', user_id=user_id, slug=slug)

        context = {
            'car': car,
            'form': form,
            'user_id': user_id,
        }

    except ObjectDoesNotExist as ex:
        return render(request, 'exception-handling/car-details-error-page.html')
    return render(request, 'cars/car-edit-page.html', context)


@login_required
def car_add(request):
    if request.method == 'GET':
        form = CarCreateForm()
    else:
        form = CarCreateForm(request.POST)
        if form.is_valid():
            car = form.save(commit=False)
            car.user = request.user
            car.save()
            return redirect('home page')
    context = {
        'form': form,
    }
    return render(request, 'cars/car-add-page.html', context)


def car_delete(request, slug, user_id):
    try:
        car = get_car_by_model_and_user_id(slug, user_id)

        if not car.user == request.user:
            return redirect('home page')

        if request.method == 'GET':
            form = CarDeleteForm(instance=car)
        else:
            form = CarDeleteForm(request.POST, instance=car)
            if form.is_valid():
                form.save()
                return redirect('home page')

        context = {
            'form': form,
            'slug': slug,
            'user_id': user_id,
        }
    except ObjectDoesNotExist as ex:
        return render(request, 'exception-handling/car-details-error-page.html')
    return render(request, 'cars/car-delete-page.html', context)

templates/cars/car-add-page.html
{% extends 'base/index.html' %}
{% load static %}
{% block page_content %}

    <div class="position-absolute top-50 start-50 translate-middle">
        <div class="shadow p-3 mb-5 bg-body rounded">
            <div class="card" style="width: 800px;">
                <div class="card-body">
                    <h5 class="card-title"><strong>Add Car</strong></h5>
                </div>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">
                        <form action="{% url 'car add' %}" method="post" class="row g-3 needs-validation">
                            <div class="col-md-4">
                                <p><strong>Type: <br>{{ form.type }}</strong></p>
                            </div>
                            <div class="col-md-4">
                                <p><strong>Model: </strong>{{ form.model }}</p>
                            </div>
                            <div class="col-md-4">
                                <p><strong>Year of production: </strong>{{ form.year_of_production }}</p>
                            </div>
                            <div class="col-md-4">
                                <p><strong>Price: </strong>{{ form.price }}</p>
                            </div>
                            <div class="col-md-4">
                                <p><strong>Horse power: </strong>{{ form.horse_power }}</p>
                            </div>
                            <div class="col-md-4">
                                <p><strong>Image URL: </strong>{{ form.image_url }}</p>
                            </div>
                            <div class="col-mb-4">
                                <p><strong>Description: </strong>{{ form.description }}</p>
                            </div>
                            <div>
                                <button type="submit" class="btn btn-primary"
                                        style="--bs-btn-padding-y: .25rem; --bs-btn-padding-x: .5rem; --bs-btn-font-size: .90rem;">
                                    Add car
                                </button>
                            </div>
                            {% csrf_token %}
                        </form>
                    </li>
                </ul>
            </div>
        </div>
    </div>

{% endblock %}

templates/cars/car-delete-page.html
{% extends 'base/index.html' %}
{% block page_content %}

    <div class="position-absolute top-50 start-50 translate-middle">
        <div class="shadow p-3 mb-5 bg-body rounded">
            <div class="card" style="width: 800px;">
                <div class="card-body">
                    <h5 class="card-title"><strong>Delete Car</strong></h5>
                </div>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">
                        <form action="{% url 'car delete' slug=slug user_id=user_id %}" method="post"
                              class="row g-3 needs-validation">
                            <div class="col-md-4">
                                <p><strong>Type: <br>{{ form.type }}</strong></p>
                            </div>
                            <div class="col-md-4">
                                <p><strong>Model: </strong>{{ form.model }}</p>
                            </div>
                            <div class="col-md-4">
                                <p><strong>Year of production: </strong>{{ form.year_of_production }}</p>
                            </div>
                            <div class="col-md-4">
                                <p><strong>Price: </strong>{{ form.price }}</p>
                            </div>
                            <div class="col-md-4">
                                <p><strong>Horse power: </strong>{{ form.horse_power }}</p>
                            </div>
                            <div class="col-md-4">
                                <p><strong>Image URL: </strong>{{ form.image_url }}</p>
                            </div>
                            <div class="col-mb-4">
                                <p><strong>Description: </strong>{{ form.description }}</p>
                            </div>
                            <div>
                                <button type="submit" class="btn btn-primary"
                                        style="--bs-btn-padding-y: .25rem; --bs-btn-padding-x: .5rem; --bs-btn-font-size: .90rem;">
                                    Delete
                                </button>
                                <a href="javascript:history.back()" class="btn btn-primary"
                                   style="--bs-btn-padding-y: .25rem; --bs-btn-padding-x: .5rem; --bs-btn-font-size: .90rem;">Back</a>
                                {% csrf_token %}
                            </div>
                            {% csrf_token %}
                        </form>
                    </li>
                </ul>
            </div>
        </div>
    </div>

{% endblock %}

templates/cars/car-details-page.html
{% extends 'base/index.html' %}
{% load static %}

{% block page_content %}

    <div class="card mb-3" style="max-width: 540px;">
        <div class="row g-0">
            <div class="col-md-4">
                <img src="{{ car.image_url }}" class="img-fluid rounded-start" alt="image of {{ car.model }}">
                <p class="likes"><strong>Likes: {{ likes_count }}</strong></p>
                <p><span class="heart">
                                    <a href="{% url 'like car' car_id=car.pk %}">
                                        {% if has_user_liked_car %}
                                            <svg style="color: red"
                                                 xmlns="http://www.w3.org/2000/svg"
                                                 width="24"
                                                 height="24"
                                                 fill="currentColor"
                                                 class="bi bi-heart-fill"
                                                 viewBox="0 0 16 16">
                                            <path fill-rule="evenodd"
                                                  d="M8 1.314C12.438-3.248 23.534 4.735
                                                  8 15-7.534 4.736 3.562-3.248 8 1.314z"
                                                  fill="red">
                                            </path>
                                        </svg>

                                        {% else %}
                                            <svg aria-label="Like"
                                                 color="#262626"
                                                 fill="#262626"
                                                 height="24"
                                                 role="img"
                                                 viewBox="0 0 48 48"
                                                 width="24">
                                        <path d="M34.6 6.1c5.7 0 10.4 5.2 10.4
                                                    11.5 0 6.8-5.9 11-11.5 16S25 41.3 24
                                                    41.9c-1.1-.7-4.7-4-9.5-8.3-5.7-5-11.5-9.2-11.5-16C3
                                                    11.3 7.7 6.1 13.4 6.1c4.2 0 6.5 2 8.1 4.3
                                                    1.9 2.6 2.2 3.9 2.5 3.9.3 0 .6-1.3 2.5-3.9
                                                    1.6-2.3 3.9-4.3 8.1-4.3m0-3c-4.5 0-7.9
                                                    1.8-10.6 5.6-2.7-3.7-6.1-5.5-10.6-5.5C6 3.1
                                                    0 9.6 0 17.6c0 7.3 5.4 12 10.6 16.5.6.5 1.3
                                                    1.1 1.9 1.7l2.3 2c4.4 3.9 6.6 5.9 7.6 6.5.5.3
                                                    1.1.5 1.6.5.6 0 1.1-.2 1.6-.5 1-.6 2.8-2.2
                                                    7.8-6.8l2-1.8c.7-.6 1.3-1.2 2-1.7C42.7 29.6
                                                    48 25 48 17.6c0-8-6-14.5-13.4-14.5z">
                                        </path>
                                        </svg>
                                        {% endif %}
								    </a>
                            </span></p>
            </div>
            <div class="col-md-8">
                <div class="card-body">
                    <h5 class="card-title"><strong>Car Details</strong></h5>
                    <div>
                        <p><strong>Model:</strong> <i>{{ car.model }}</i></p>
                        <p><strong>Type:</strong> <i>{{ car.type }}</i></p>
                        <p><strong>Horse power:</strong> <i>{{ car.horse_power }}</i></p>
                        <p><strong>Year of production:</strong> <i>{{ car.year_of_production }}</i></p>
                        <p><strong>Price:</strong> <i>{{ car.price|floatformat:2 }} $</i></p>
                        {% if car.description %}
                            <p><strong>Description:</strong> <i>{{ car.description }}</i></p>
                        {% endif %}

                        {% if is_owner %}
                            <a href="{% url 'car edit' slug=car.slug user_id=car.user.id %}"
                               class="btn btn-primary"
                               style="--bs-btn-padding-y: .25rem; --bs-btn-padding-x: .5rem; --bs-btn-font-size: .90rem;">Edit</a>
                            <a href="{% url 'car delete' slug=car.slug user_id=car.user.id %}"
                               class="btn btn-primary"
                               style="--bs-btn-padding-y: .25rem; --bs-btn-padding-x: .5rem; --bs-btn-font-size: .90rem;">Delete</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="row row-cols-1 row-cols-md-3 g-4">
        <div class="col">
            <div class="card h-100">
                <div class="card-body">
                    <h5 class="card-title">Comments</h5>
                    <div>
                        <ul>
                            <div class="cut-part-of-email">{{ test_drive.user.email }}
                                <i>{{ test_drive.test_drive_date }}</i></div>
                            {% for comment in car.carcomment_set.all %}
                                <div class="hstack gap-3">
                                    <div class="form-control me-auto" type="text">
                                        <p class="cut-part-of-email">{{ request.user.email }}: {{ comment.text }}</p>
                                    </div>
                                    <span style="color:#82A1C1">{{ comment.publication_date_and_time }}</span>
                                </div>
                            {% endfor %}
                        </ul>
                    </div>
                    <div class="addComments">
                        <form method="post" action="{% url 'add comment' car_id=car.pk %}">
                            {{ comment_form }}
                            <button type="submit" class="btn btn-primary"
                                    style="--bs-btn-padding-y: .25rem; --bs-btn-padding-x: .5rem; --bs-btn-font-size: .90rem;">
                                Post
                            </button>
                            {% csrf_token %}
                        </form>
                    </div>
                </div>
            </div>
        </div>

        <div class="col">
            <div class="card h-100">
                <div class="card-body">
                    <h5 class="card-title">Test drive chart</h5>
                    <div>
                        {% if car.cartestdrive_set %}
                            <ul>
                                {% for test_drive in car.cartestdrive_set.all %}
                                    <div class="hstack gap-3">
                                        <div class="form-control me-auto" type="text">
                                            <div class="cut-part-of-email">{{ test_drive.user.email }}:
                                                <i>{{ test_drive.test_drive_date }}</i></div>
                                        </div>
                                        {% if test_drive.user.pk == request.user.pk %}
                                            <a href="{% url 'edit test drive' car_id=car.pk %}"
                                               class="btn btn-primary"
                                               style="--bs-btn-padding-y: .25rem; --bs-btn-padding-x: .5rem; --bs-btn-font-size: .90rem;">Edit</a>
                                            <a href="{% url 'delete test drive' car_id=car.pk %}"
                                               class="btn btn-primary"
                                               style="--bs-btn-padding-y: .25rem; --bs-btn-padding-x: .5rem; --bs-btn-font-size: .90rem;">Delete</a>
                                        {% endif %}
                                    </div>
                                {% endfor %}
                            </ul>
                            <div>
                                <br>
                                {% if not is_owner %}
                                    {% if user_has_test_drive %}
                                        <a href="{% url 'test drive' car_id=car.pk %}"
                                           class="btn btn-primary"
                                           style="--bs-btn-padding-y: .25rem; --bs-btn-padding-x: .5rem; --bs-btn-font-size: .90rem;">Test
                                            Drive</a>
                                    {% endif %}
                                {% endif %}
                            </div>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script>
        for (let i = 0; i < document.getElementsByClassName('cut-part-of-email').length; i++) {
            let currentP = document.getElementsByClassName('cut-part-of-email')[i].innerHTML.toString()
            let emailPart = currentP.substring(0, currentP.indexOf('@'))
            emailPart = emailPart.charAt(0).toUpperCase() + emailPart.slice(1)
            let textPart = currentP.substring(currentP.indexOf(':'))
            document.getElementsByClassName('cut-part-of-email')[i].innerHTML = emailPart + textPart
        }
    </script>

{% endblock %}

templates/cars/car-edit-page.html
{% extends 'base/index.html' %}
{% block page_content %}

    <div class="position-absolute top-50 start-50 translate-middle">
        <div class="shadow p-3 mb-5 bg-body rounded">
            <div class="card" style="width: 800px;">
                <div class="card-body">
                    <h5 class="card-title"><strong>Edit Car</strong></h5>
                </div>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">
                        <form action="{% url 'car edit' slug=car.slug user_id=user_id %}" method="post"
                              class="row g-3 needs-validation">
                            <div class="col-md-4">
                                <p><strong>Type: <br>{{ form.type }}</strong></p>
                            </div>
                            <div class="col-md-4">
                                <p><strong>Model: </strong>{{ form.model }}</p>
                            </div>
                            <div class="col-md-4">
                                <p><strong>Year of production: </strong>{{ form.year_of_production }}</p>
                            </div>
                            <div class="col-md-4">
                                <p><strong>Price: </strong>{{ form.price }}</p>
                            </div>
                            <div class="col-md-4">
                                <p><strong>Horse power: </strong>{{ form.horse_power }}</p>
                            </div>
                            <div class="col-md-4">
                                <p><strong>Image URL: </strong>{{ form.image_url }}</p>
                            </div>
                            <div class="col-mb-4">
                                <p><strong>Description: </strong>{{ form.description }}</p>
                            </div>
                            <div>
                                <button type="submit" class="btn btn-primary"
                                        style="--bs-btn-padding-y: .25rem; --bs-btn-padding-x: .5rem; --bs-btn-font-size: .90rem;">
                                    Edit
                                </button>
                                <a href="javascript:history.back()" class="btn btn-primary"
                                   style="--bs-btn-padding-y: .25rem; --bs-btn-padding-x: .5rem; --bs-btn-font-size: .90rem;">Back</a>
                                {% csrf_token %}
                            </div>
                            {% csrf_token %}
                        </form>
                    </li>
                </ul>
            </div>
        </div>
    </div>

{% endblock %}